version: '3.4'

services:
  node:
    image: node
    container_name: api-investimentos
    working_dir: /app
    volumes:
      - ./:/app
    tty: true
    stdin_open: true
    command: bash
    restart: always
    depends_on:
    - db
    ports:
      - 3000:3000
    environment:
      DB_USERNAME: root
      PASSWORD_POSTGRES: password
      HOST: db
      JWT_SECRET: secretJWT
  db:
    container_name: api-investimentos-db
    image: mysql:8.0.21
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password